feat: candidate-details + candidate history functionality
zzzoomprism/hr-automation-ui pull request #5
Opened 2022-06-28 07:57 UTC by KavMip

Candidate details information added to app.
Added candidate history functionality.

2022-07-01 10:31 UTC, AlexKolonitskyMifort requested changes

2022-07-11 10:28 UTC, AlexKolonitskyMifort requested changes

2022-07-12 18:05 UTC, Smithpovvi commented on src/app/components/shared/edit-candidate-modal/edit-candidate-modal.component.ts
> +            // TODO: Need to think, maybe we should subscribe in service and call just this.candidateService.getCandidateById();
Убрал

2022-07-12 18:06 UTC, Smithpovvi commented on src/app/pages/candidate-detail/candidate-detail.component.ts
> +    if (this.candidateId) {
пофиксил

2022-07-12 18:07 UTC, vladislavbairash commented on src/app/pages/candidate-detail/candidate-detail.component.ts
> +        .pipe(take(1))
Потому что сервис запровайден в candidate-details.component и нам нужно получать только один раз

2022-07-12 18:07 UTC, Smithpovvi commented on src/app/pages/candidate-detail/candidate-detail.component.ts
> +          error: (error) => {
Сделали с тобой

2022-07-12 18:08 UTC, Smithpovvi commented on src/app/services/candidateDetail.service.ts
> +            candidate.candidateAttributes.map((attribute: CandidateAttribute) => {
Это уже не актуально, мы с тобой переделали логику

2022-07-12 18:08 UTC, Smithpovvi commented on src/app/services/candidateDetail.service.ts
> +          this.notification.show(
готово

2022-07-12 18:08 UTC, vladislavbairash commented on src/app/services/candidateDetail.service.ts
> +  public currentCandidate$: BehaviorSubject<Candidate | null> =
в этом кейсе нужен паблик для доступа из копонентов

2022-07-12 18:09 UTC, vladislavbairash commented on src/app/services/candidateDetail.service.ts
> +  public historyOfCurrentCandidate$: BehaviorSubject<HistoryElement[] | null> = new BehaviorSubject<
в этом кейсе нужен паблик для доступа из копонентов

2022-07-12 18:09 UTC, vladislavbairash commented on src/app/services/candidateDetail.service.ts
> +  public candidateAttributes$: BehaviorSubject<CandidateAttributesValues[] | null> =
в этом кейсе нужен паблик для доступа из копонентов

2022-07-13 08:21 UTC, AlexKolonitskyMifort approved these changes

2022-07-13 08:21 UTC, merged